excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

disabled_rules:
- force_cast
- file_length

variable_name:
  min_length:            # only min_length
    error: 4             # only error
  excluded:              # excluded via string array
    - id
    - ids
    - URL
    - i
    - row
    - lat
    - long
    - url
